platform :ios , '9.0'
target 'HXTest' do  

pod "Masonry"
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SDWebImage', '~> 4.0'
pod 'SDWebImage/GIF'
pod 'IQKeyboardManager'
pod 'FLAnimatedImage'
pod 'Hyphenate'

end